repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
    -   id: black
-   repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args:
        -   "--multi-line=3"
        -   "--trailing-comma"
        -   "--force-grid-wrap=0"
        -   "--use-parentheses"
        -   "--ensure-newline-before-comments"
        -   "--line-length=88"
-   repo: https://github.com/pycqa/flake8
    rev:  7.1.1
    hooks:
    -   id: flake8
        args:
        -   --max-line-length=88
        -   --extend-select=B950
        -   --extend-ignore=E203,E501,E701
        additional_dependencies:
        -   flake8-bugbear
